spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates: [ Path=/auth/** ]
        - id: catalog
          uri: http://localhost:8083
          predicates: [ Path=/catalog/** ]
        - id: cart
          uri: http://localhost:8085
          predicates: [ Path=/cart/** ]
        - id: order
          uri: http://localhost:8086
          predicates: [ Path=/order/** ]
        - id: payment
          uri: http://localhost:8087
          predicates: [ Path=/payment/** ]
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
